version: '3.9'

services:
  mosquitto:
    container_name: mqtt
    image: magisterka-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - ./src:/mosquitto/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  config:
  data:
  log: